language: julia
julia:
  - release
  - nightly
  - 0.4

# Need to install a Fortran compiler for Dierckx and RADMC-3D depedency
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gfortran
  - export PATH=$PATH:$PWD/JudithExcalibur/scripts # add the scripts/ directory

# This the default script that is run
# julia -e 'Pkg.clone(pwd())'
# julia -e 'Pkg.build("$name")'
# if [ -f test/runtests.jl ]; then
#   julia --check-bounds=yes -e 'Pkg.test("$name", coverage=true)'
# fi
